export {
  TAB,
  FORM_REFS,
  POLICY_DEFAULTS,
  DATA_PRIVACY_FORM_SETTINGS,
  POLICY_HW_ATTESTATION_SECURITY_LEVEL,
  POLICY_SMS_SCANNING_OPTIONS,
  POLICY_WARNING_NOTIFICATION_INTERVAL,
  NOTIFY_SUFFIX,
  UNRESPONSIVE_AGENT_MAX_VALUE,
  UNRESPONSIVE_AGENT_MIN_VALUE,
} from './view/common/settings'

export { getI18EnumName, getI18Name } from './view/common/i18n'
