// --TODO: DELETE THIS
import type { FlattenedDevicePolicy } from '@ues-data/epp'

const MOCK_EXISTING_FLATTENED_POLICY: FlattenedDevicePolicy = {
  file_exclusions: [
    {
      file_type: 1,
      file_name: 'MD TEST',
      av_industry: false,
      reason: 'TEST TEST TEST',
      infinity: null,
      research_subclass_id: '0',
      cloud_score: 50,
      file_hash: 'da84e5104ec02982515127adda821ffc533acf7f07bd9b5839f31239e888feea',
      research_class_id: '1',
      md5: 'd9729feb74992cc3482b350163a1a010',
      category_id: '2',
    },
    {
      research_subclass_id: '4',
      cloud_score: 25,
      file_hash: 'da84e5104ec02982515127adda821ffc533acf7f07bd9b5839f31239e888feee',
      category_id: '7',
      file_name: 'MD TEST 2',
      reason: 'TSET TEST TEST',
      av_industry: false,
      infinity: null,
      research_class_id: '2',
      file_type: 1,
      md5: 'd9729feb74992cc3482b350163a1a010',
    },
    {
      file_hash: '18ee24150dcb1d96752a4d6dd0f20dfd8ba8c38527e40aa8509b7adecf78f9c6',
      cloud_score: 1,
      reason: 'sddsdfasdfsadf',
      md5: null,
      file_type: 1,
      file_name: '',
      category_id: '1',
      av_industry: false,
      infinity: null,
      research_class_id: '0',
      research_subclass_id: '13',
    },
    {
      file_hash: '28ee24150dcb1d96752a4d6dd0f20dfd8ba8c38527e40aa8509b7adecf78f9c6',
      cloud_score: 100,
      reason: 'sddsdfasdfsadf',
      md5: null,
      file_type: 1,
      file_name: 'Test 1',
      category_id: '1',
      av_industry: false,
      infinity: null,
      research_class_id: '1',
      research_subclass_id: '1',
    },
    {
      file_hash: '38ee24150dcb1d96752a4d6dd0f20dfd8ba8c38527e40aa8509b7adecf78f9c6',
      cloud_score: null,
      reason: 'sddsdfasdfsadf',
      md5: null,
      file_type: 1,
      file_name: 'Test 2',
      category_id: '1',
      av_industry: false,
      infinity: null,
      research_class_id: '2',
      research_subclass_id: '2',
    },
    {
      file_hash: '48ee24150dcb1d96752a4d6dd0f20dfd8ba8c38527e40aa8509b7adecf78f9c6',
      cloud_score: 75,
      reason: 'sddsdfasdfsadf',
      md5: null,
      file_type: 1,
      file_name: 'Test 3',
      category_id: '1',
      av_industry: false,
      infinity: null,
      research_class_id: '3',
      research_subclass_id: '3',
    },
    {
      file_hash: '58ee24150dcb1d96752a4d6dd0f20dfd8ba8c38527e40aa8509b7adecf78f9c6',
      cloud_score: null,
      reason: 'sddsdfasdfsadf',
      md5: null,
      file_type: 1,
      file_name: 'Test 4',
      category_id: '1',
      av_industry: false,
      infinity: null,
      research_class_id: '4',
      research_subclass_id: '5',
    },
    {
      file_hash: '68ee24150dcb1d96752a4d6dd0f20dfd8ba8c38527e40aa8509b7adecf78f9c6',
      cloud_score: 88,
      reason: 'sddsdfasdfsadf',
      md5: null,
      file_type: 1,
      file_name: 'Test 5',
      category_id: '1',
      av_industry: false,
      infinity: null,
      research_class_id: '5',
      research_subclass_id: '6',
    },
    {
      file_hash: '78ee24150dcb1d96752a4d6dd0f20dfd8ba8c38527e40aa8509b7adecf78f9c6',
      cloud_score: 22,
      reason: 'sddsdfasdfsadf',
      md5: null,
      file_type: 1,
      file_name: 'Test 6',
      category_id: '1',
      av_industry: false,
      infinity: null,
      research_class_id: '6',
      research_subclass_id: '7',
    },
    {
      file_hash: '88ee24150dcb1d96752a4d6dd0f20dfd8ba8c38527e40aa8509b7adecf78f9c6',
      cloud_score: null,
      reason: 'sddsdfasdfsadf',
      md5: null,
      file_type: 1,
      file_name: 'Test 7',
      category_id: '1',
      av_industry: false,
      infinity: null,
      research_class_id: '0',
      research_subclass_id: '8',
    },
    {
      file_hash: '98ee24150dcb1d96752a4d6dd0f20dfd8ba8c38527e40aa8509b7adecf78f9c6',
      cloud_score: 5,
      reason: 'sddsdfasdfsadf',
      md5: null,
      file_type: 1,
      file_name: 'Test 8',
      category_id: '1',
      av_industry: false,
      infinity: null,
      research_class_id: '0',
      research_subclass_id: '9',
    },
  ],
  'filetype_actions.suspicious_files[0].actions': '1',
  'filetype_actions.suspicious_files[0].file_type': 'executable',
  'filetype_actions.threat_files[0].actions': '1',
  'filetype_actions.threat_files[0].file_type': 'executable',
  policy_name: 'A Super Cool Policy',
  policy_id: '8868efa4-50ab-4ede-a0ca-a94652ecabda',
  checksum: 'f83fd799df47e0d208addb6342d1a80e',
  policy_utctimestamp: '2020-02-25T19:21:13.686+00:00',
  'device_control.configurations[0].device_class': 'AndroidUSB',
  'device_control.configurations[0].control_mode': 'FullAccess',
  'device_control.configurations[1].control_mode': 'FullAccess',
  'device_control.configurations[1].device_class': 'iOS',
  'device_control.configurations[2].device_class': 'StillImage',
  'device_control.configurations[2].control_mode': 'FullAccess',
  'device_control.configurations[3].control_mode': 'FullAccess',
  'device_control.configurations[3].device_class': 'USBCDDVDRW',
  'device_control.configurations[4].device_class': 'USBDrive',
  'device_control.configurations[4].control_mode': 'FullAccess',
  'device_control.configurations[5].control_mode': 'FullAccess',
  'device_control.configurations[5].device_class': 'VMWareMount',
  'device_control.configurations[6].device_class': 'WPD',
  'device_control.configurations[6].control_mode': 'FullAccess',
  'device_control.exclusion_list': [
    {
      comment: 'test',
      control_mode: 'FullAccess',
      date_added: '2021-08-23T19:12:47.786Z',
      product_id: '222',
      serial_number: '333',
      vendor_id: '111',
    },
    {
      comment: '',
      control_mode: 'FullAccess',
      date_added: '2021-07-23T19:12:47.786Z',
      product_id: '',
      serial_number: '333',
      vendor_id: '123',
    },
    {
      comment: 'blah',
      control_mode: 'Block',
      date_added: '2021-06-23T19:12:47.786Z',
      product_id: '233',
      serial_number: '',
      vendor_id: '444',
    },
    {
      comment: 'test 4',
      control_mode: 'ReadOnly',
      date_added: '2021-05-23T19:12:47.786Z',
      product_id: '225',
      serial_number: '555',
      vendor_id: '343',
    },
  ],
  'policy[0].value': '1',
  'policy[0].name': 'auto_blocking',
  'policy[1].name': 'auto_uploading',
  'policy[1].value': '0',
  'policy[2].value': '500',
  'policy[2].name': 'threat_report_limit',
  'policy[3].value': '-600',
  'policy[3].name': 'low_confidence_threshold',
  'policy[4].value': '0',
  'policy[4].name': 'full_disc_scan',
  'policy[5].name': 'watch_for_new_files',
  'policy[5].value': '1',
  'policy[6].name': 'memory_exploit_detection',
  'policy[6].value': '1',
  'policy[7].value': '0',
  'policy[7].name': 'trust_files_in_scan_exception_list',
  'policy[8].value': '1',
  'policy[8].name': 'logpolicy',
  'policy[9].name': 'script_control',
  'policy[9].value': '1',
  'policy[10].value': '0',
  'policy[10].name': 'prevent_service_shutdown',
  'policy[11].name': 'scan_max_archive_size',
  'policy[11].value': '0',
  'policy[12].value': null,
  'policy[12].name': 'sample_copy_path',
  'policy[13].value': '0',
  'policy[13].name': 'kill_running_threats',
  'policy[14].value': '1',
  'policy[14].name': 'show_notifications',
  'policy[15].name': 'optics_set_disk_usage_maximum_fixed',
  'policy[15].value': '700',
  'policy[16].value': '1',
  'policy[16].name': 'optics_malware_auto_upload',
  'policy[17].value': '0',
  'policy[17].name': 'optics_memory_defense_auto_upload',
  'policy[18].name': 'optics_script_control_auto_upload',
  'policy[18].value': '0',
  'policy[19].name': 'optics_application_control_auto_upload',
  'policy[19].value': '0',
  'policy[20].value': '0',
  'policy[20].name': 'optics_sensors_dns_visibility',
  'policy[21].name': 'optics_sensors_private_network_address_visibility',
  'policy[21].value': '0',
  'policy[22].value': '1',
  'policy[22].name': 'optics_sensors_windows_event_log_visibility',
  'policy[23].value': '0',
  'policy[23].name': 'optics_sensors_advanced_powershell_visibility',
  'policy[24].name': 'optics_sensors_advanced_wmi_visibility',
  'policy[24].value': '1',
  'policy[25].name': 'optics_sensors_advanced_executable_parsing',
  'policy[25].value': '0',
  'policy[26].name': 'optics_sensors_enhanced_process_hooking_visibility',
  'policy[26].value': '0',
  'policy[27].name': 'device_control',
  'policy[27].value': '1',
  'policy[28].value': '1',
  'policy[28].name': 'optics',
  'policy[29].value': '1',
  'policy[29].name': 'optics_show_notifications',
  'policy[30].name': 'auto_delete',
  'policy[30].value': '0',
  'policy[31].value': '14',
  'policy[31].name': 'days_until_deleted',
  'policy[32].name': 'pdf_auto_uploading',
  'policy[32].value': '0',
  'policy[33].value': '0',
  'policy[33].name': 'ole_auto_uploading',
  'policy[34].name': 'docx_auto_uploading',
  'policy[34].value': '0',
  'policy[35].name': 'python_auto_uploading',
  'policy[35].value': '0',
  'policy[36].name': 'autoit_auto_uploading',
  'policy[36].value': '0',
  'policy[37].name': 'powershell_auto_uploading',
  'policy[37].value': '0',
  'policy[38].name': 'data_privacy',
  'policy[38].value': '0',
  'policy[39].name': 'custom_thumbprint',
  'policy[39].value': null,
  'policy[40].name': 'scan_exception_list',
  'policy[40].value': [
    '/test1',
    '/test2',
    '/test3',
    '/test4',
    '/test5',
    '/test6',
    '/test7',
    '/test8',
    '/test9',
    '/test10',
    '/test11',
    '/test12',
    '/test13',
    '/test14',
    '/test15',
    '/test16',
    '/test17',
    '/test18',
    '/test19',
    '/test20',
    '/test21',
    '/test22',
    '/test23',
  ],
  'policy[41].name': 'optics_sensors_intel_cryptomining_detection',
  'policy[41].value': '0',
  'memoryviolation_actions.memory_exclusion_list': [
    '/test.exe',
    '/test2.exe',
    '/test3.exe',
    '/test4.exe',
    '/test5.exe',
    '/test6.exe',
    '/test7.exe',
    '/test8.exe',
    '/test_all.exe',
    '/test9.exe',
    '/test10.exe',
    '/test11.exe',
    '/test12.exe',
    '/test13.exe',
    '/test14.exe',
    '/test15.exe',
    '/test16.exe',
    '/test17.exe',
    '/test18.exe',
    '/test19.exe',
    '/test20.exe',
    '/test21.exe',
    '/test22.exe',
  ],
  'memoryviolation_actions.memory_exclusion_list_v2': [
    {
      id: 'memoryviolation_actions.memory_exclusion_list_v21',
      path: '/test.exe',
      violations: [
        {
          action: 'None',
          violation_type: 'stackpivot',
        },
        {
          action: 'None',
          violation_type: 'systemdllwrite',
        },
        {
          action: 'None',
          violation_type: 'outofprocessunmapmemory',
        },
        {
          action: 'None',
          violation_type: 'lsassread',
        },
      ],
    },
    {
      id: 'memoryviolation_actions.memory_exclusion_list_v22',
      path: '/test2.exe',
      violations: [],
    },
    {
      id: 'memoryviolation_actions.memory_exclusion_list_v23',
      path: '/test3.exe',
      violations: [
        {
          action: 'None',
          violation_type: 'dangerouscomobject',
        },
        {
          action: 'None',
          violation_type: 'outofprocessmap',
        },
        {
          action: 'None',
          violation_type: 'outofprocessunmapmemory',
        },
      ],
    },
    {
      id: 'memoryviolation_actions.memory_exclusion_list_v24',
      path: '/test4.exe',
      violations: [],
    },
    {
      id: 'memoryviolation_actions.memory_exclusion_list_v25',
      path: '/test5.exe',
      violations: [],
    },
    {
      id: 'memoryviolation_actions.memory_exclusion_list_v26',
      path: '/test6.exe',
      violations: [],
    },
    {
      id: 'memoryviolation_actions.memory_exclusion_list_v27',
      path: '/test7.exe',
      violations: [
        {
          action: 'None',
          violation_type: 'dangerouscomobject',
        },
        {
          action: 'None',
          violation_type: 'outofprocessmap',
        },
        {
          action: 'None',
          violation_type: 'outofprocessunmapmemory',
        },
        {
          action: 'None',
          violation_type: 'stackpivot',
        },
        {
          action: 'None',
          violation_type: 'systemdllwrite',
        },
        {
          action: 'None',
          violation_type: 'outofprocessunmapmemory',
        },
        {
          action: 'None',
          violation_type: 'lsassread',
        },
      ],
    },
    {
      id: 'memoryviolation_actions.memory_exclusion_list_v28',
      path: '/test8.exe',
      violations: [
        {
          action: 'None',
          violation_type: 'outofprocessapc',
        },
      ],
    },
    {
      id: 'memoryviolation_actions.memory_exclusion_list_v29',
      path: '/test_all.exe',
      violations: [
        {
          action: 'None',
          violation_type: 'stackpivot',
        },
        {
          action: 'None',
          violation_type: 'stackprotect',
        },
        {
          action: 'None',
          violation_type: 'lsassread',
        },
        {
          action: 'None',
          violation_type: 'overwritecode',
        },
        {
          action: 'None',
          violation_type: 'outofprocessunmapmemory',
        },
        {
          action: 'None',
          violation_type: 'outofprocessoverwritecode',
        },
        {
          action: 'None',
          violation_type: 'outofprocesscreatethread',
        },
        {
          action: 'None',
          violation_type: 'outofprocesswritepe',
        },
        {
          action: 'None',
          violation_type: 'outofprocessallocation',
        },
        {
          action: 'None',
          violation_type: 'outofprocessmap',
        },
        {
          action: 'None',
          violation_type: 'outofprocesswrite',
        },
        {
          action: 'None',
          violation_type: 'outofprocessapc',
        },
        {
          action: 'None',
          violation_type: 'dyldinjection',
        },
        {
          action: 'None',
          violation_type: 'trackdataread',
        },
        {
          action: 'None',
          violation_type: 'zeroallocate',
        },
        {
          action: 'None',
          violation_type: 'maliciouspayload',
        },
        {
          action: 'None',
          violation_type: 'runmacroscript',
        },
        {
          action: 'None',
          violation_type: 'doppelganger',
        },
        {
          action: 'None',
          violation_type: 'oopprotect',
        },
        {
          action: 'None',
          violation_type: 'childprocessprotect',
        },
        {
          action: 'None',
          violation_type: 'syscallprobe',
        },
        {
          action: 'None',
          violation_type: 'directsyscall',
        },
        {
          action: 'None',
          violation_type: 'systemdllwrite',
        },
        {
          action: 'None',
          violation_type: 'stolensystemtoken',
        },
        {
          action: 'None',
          violation_type: 'dangerousenvvariable',
        },
        {
          action: 'None',
          violation_type: 'maliciouslowintegrity',
        },
        {
          action: 'None',
          violation_type: 'dangerouscomobject',
        },
        {
          action: 'None',
          violation_type: 'injectionviaapc',
        },
      ],
    },
    {
      id: 'memoryviolation_actions.memory_exclusion_list_v210',
      path: '/test9.exe',
      violations: [
        {
          action: 'None',
          violation_type: 'stackpivot',
        },
        {
          action: 'None',
          violation_type: 'stackprotect',
        },
        {
          action: 'None',
          violation_type: 'lsassread',
        },
        {
          action: 'None',
          violation_type: 'overwritecode',
        },
        {
          action: 'None',
          violation_type: 'outofprocessunmapmemory',
        },
        {
          action: 'None',
          violation_type: 'outofprocessoverwritecode',
        },
        {
          action: 'None',
          violation_type: 'outofprocesscreatethread',
        },
        {
          action: 'None',
          violation_type: 'outofprocesswritepe',
        },
        {
          action: 'None',
          violation_type: 'outofprocessallocation',
        },
        {
          action: 'None',
          violation_type: 'outofprocessmap',
        },
        {
          action: 'None',
          violation_type: 'outofprocesswrite',
        },
        {
          action: 'None',
          violation_type: 'outofprocessapc',
        },
        {
          action: 'None',
          violation_type: 'dyldinjection',
        },
        {
          action: 'None',
          violation_type: 'trackdataread',
        },
        {
          action: 'None',
          violation_type: 'zeroallocate',
        },
        {
          action: 'None',
          violation_type: 'maliciouspayload',
        },
      ],
    },
    {
      id: 'memoryviolation_actions.memory_exclusion_list_v211',
      path: '/test10.exe',
      violations: [
        {
          action: 'None',
          violation_type: 'stackpivot',
        },
        {
          action: 'None',
          violation_type: 'stackprotect',
        },
        {
          action: 'None',
          violation_type: 'lsassread',
        },
        {
          action: 'None',
          violation_type: 'overwritecode',
        },
        {
          action: 'None',
          violation_type: 'dyldinjection',
        },
        {
          action: 'None',
          violation_type: 'trackdataread',
        },
        {
          action: 'None',
          violation_type: 'zeroallocate',
        },
        {
          action: 'None',
          violation_type: 'maliciouspayload',
        },
      ],
    },
    {
      id: 'memoryviolation_actions.memory_exclusion_list_v212',
      path: '/test11.exe',
      violations: [],
    },
    {
      id: 'memoryviolation_actions.memory_exclusion_list_v213',
      path: '/test12.exe',
      violations: [
        {
          action: 'None',
          violation_type: 'stackpivot',
        },
        {
          action: 'None',
          violation_type: 'overwritecode',
        },
        {
          action: 'None',
          violation_type: 'dyldinjection',
        },
        {
          action: 'None',
          violation_type: 'maliciouspayload',
        },
      ],
    },
    {
      id: 'memoryviolation_actions.memory_exclusion_list_v214',
      path: '/test13.exe',
      violations: [],
    },
    {
      id: 'memoryviolation_actions.memory_exclusion_list_v215',
      path: '/test14.exe',
      violations: [],
    },
    {
      id: 'memoryviolation_actions.memory_exclusion_list_v216',
      path: '/test15.exe',
      violations: [],
    },
    {
      id: 'memoryviolation_actions.memory_exclusion_list_v217',
      path: '/test16.exe',
      violations: [
        {
          action: 'None',
          violation_type: 'stackpivot',
        },
        {
          action: 'None',
          violation_type: 'maliciouspayload',
        },
      ],
    },
    {
      id: 'memoryviolation_actions.memory_exclusion_list_v218',
      path: '/test17.exe',
      violations: [
        {
          action: 'None',
          violation_type: 'maliciouspayload',
        },
      ],
    },
    {
      id: 'memoryviolation_actions.memory_exclusion_list_v219',
      path: '/test18.exe',
      violations: [
        {
          action: 'None',
          violation_type: 'overwritecode',
        },
      ],
    },
    {
      id: 'memoryviolation_actions.memory_exclusion_list_v220',
      path: '/test19.exe',
      violations: [],
    },
    {
      id: 'memoryviolation_actions.memory_exclusion_list_v221',
      path: '/test20.exe',
      violations: [],
    },
    {
      id: 'memoryviolation_actions.memory_exclusion_list_v222',
      path: '/test21.exe',
      violations: [],
    },
    {
      id: 'memoryviolation_actions.memory_exclusion_list_v223',
      path: '/test22.exe',
      violations: [
        {
          action: 'None',
          violation_type: 'stackpivot',
        },
        {
          action: 'None',
          violation_type: 'overwritecode',
        },
        {
          action: 'None',
          violation_type: 'dyldinjection',
        },
        {
          action: 'None',
          violation_type: 'maliciouspayload',
        },
      ],
    },
  ],
  'memoryviolation_actions.memory_violations[0].violation_type': 'lsassread',
  'memoryviolation_actions.memory_violations[0].action': 'Terminate',
  'memoryviolation_actions.memory_violations[1].violation_type': 'outofprocessunmapmemory',
  'memoryviolation_actions.memory_violations[1].action': 'Terminate',
  'memoryviolation_actions.memory_violations[2].action': 'Terminate',
  'memoryviolation_actions.memory_violations[2].violation_type': 'stackpivot',
  'memoryviolation_actions.memory_violations[3].action': 'Terminate',
  'memoryviolation_actions.memory_violations[3].violation_type': 'stackprotect',
  'memoryviolation_actions.memory_violations[4].action': 'Terminate',
  'memoryviolation_actions.memory_violations[4].violation_type': 'outofprocessoverwritecode',
  'memoryviolation_actions.memory_violations[5].violation_type': 'outofprocesscreatethread',
  'memoryviolation_actions.memory_violations[5].action': 'Terminate',
  'memoryviolation_actions.memory_violations[6].action': 'Terminate',
  'memoryviolation_actions.memory_violations[6].violation_type': 'overwritecode',
  'memoryviolation_actions.memory_violations[7].violation_type': 'outofprocesswritepe',
  'memoryviolation_actions.memory_violations[7].action': 'Terminate',
  'memoryviolation_actions.memory_violations[8].violation_type': 'outofprocessallocation',
  'memoryviolation_actions.memory_violations[8].action': 'Terminate',
  'memoryviolation_actions.memory_violations[9].action': 'Terminate',
  'memoryviolation_actions.memory_violations[9].violation_type': 'outofprocessmap',
  'memoryviolation_actions.memory_violations[10].violation_type': 'outofprocesswrite',
  'memoryviolation_actions.memory_violations[10].action': 'Terminate',
  'memoryviolation_actions.memory_violations[11].violation_type': 'outofprocessapc',
  'memoryviolation_actions.memory_violations[11].action': 'Terminate',
  'memoryviolation_actions.memory_violations_ext[0].action': 'Terminate',
  'memoryviolation_actions.memory_violations_ext[0].violation_type': 'dyldinjection',
  'memoryviolation_actions.memory_violations_ext[1].action': 'Terminate',
  'memoryviolation_actions.memory_violations_ext[1].violation_type': 'trackdataread',
  'memoryviolation_actions.memory_violations_ext[2].violation_type': 'zeroallocate',
  'memoryviolation_actions.memory_violations_ext[2].action': 'Terminate',
  'memoryviolation_actions.memory_violations_ext[3].action': 'Terminate',
  'memoryviolation_actions.memory_violations_ext[3].violation_type': 'maliciouspayload',
  'memoryviolation_actions.memory_violations_ext_v2[0].action': 'Terminate',
  'memoryviolation_actions.memory_violations_ext_v2[0].violation_type': 'syscallprobe',
  'memoryviolation_actions.memory_violations_ext_v2[1].action': 'Terminate',
  'memoryviolation_actions.memory_violations_ext_v2[1].violation_type': 'directsyscall',
  'memoryviolation_actions.memory_violations_ext_v2[2].action': 'Terminate',
  'memoryviolation_actions.memory_violations_ext_v2[2].violation_type': 'systemdllwrite',
  'memoryviolation_actions.memory_violations_ext_v2[3].action': 'Terminate',
  'memoryviolation_actions.memory_violations_ext_v2[3].violation_type': 'dangerouscomobject',
  'memoryviolation_actions.memory_violations_ext_v2[4].action': 'Terminate',
  'memoryviolation_actions.memory_violations_ext_v2[4].violation_type': 'doppelganger',
  'memoryviolation_actions.memory_violations_ext_v2[5].action': 'Terminate',
  'memoryviolation_actions.memory_violations_ext_v2[5].violation_type': 'dangerousenvvariable',
  'memoryviolation_actions.memory_violations_ext_v2[6].action': 'Terminate',
  'memoryviolation_actions.memory_violations_ext_v2[6].violation_type': 'oopprotect',
  'memoryviolation_actions.memory_violations_ext_v2[7].action': 'Terminate',
  'memoryviolation_actions.memory_violations_ext_v2[7].violation_type': 'childprocessprotect',
  'memoryviolation_actions.memory_violations_ext_v2[8].action': 'Terminate',
  'memoryviolation_actions.memory_violations_ext_v2[8].violation_type': 'stolensystemtoken',
  'memoryviolation_actions.memory_violations_ext_v2[9].action': 'Terminate',
  'memoryviolation_actions.memory_violations_ext_v2[9].violation_type': 'maliciouslowintegrity',
  'memoryviolation_actions.memory_violations_ext_v2[10].action': 'None',
  'memoryviolation_actions.memory_violations_ext_v2[10].violation_type': 'injectionviaapc',
  'memoryviolation_actions.memory_violations_ext_v2[11].violation_type': 'runmacroscript',
  'memoryviolation_actions.memory_violations_ext_v2[11].action': 'Alert',
  'logpolicy.retentiondays': '30',
  'logpolicy.maxlogsize': '100',
  'logpolicy.log_upload.delete': 'False',
  'logpolicy.log_upload.compress': 'True',
  'appcontrol.changewindow_enabled': '0',
  'appcontrol.allowed_folders': [
    '/test1',
    '/test2',
    '/test3',
    '/test4',
    '/test5',
    '/test6',
    '/test7',
    '/test8',
    '/test9',
    '/test10',
    '/test11',
    '/test12',
    '/test13',
  ],
  'appcontrol.lockdown': [
    {
      lockdown_type: 'executionfromexternaldrives',
      action: 'deny',
    },
    {
      lockdown_type: 'pechange',
      action: 'deny',
    },
  ],
  'script_control.global_settings.allowed_folders': [
    '/[CySc_process]/ /windows/folder/example.exe',
    '/test/folder/example.exe',
    '/test/folder/example.py',
  ],
  'script_control.global_settings.control_mode': 'Alert',
  'script_control.activescript_settings.control_mode': 'Alert',
  'script_control.macro_settings.control_mode': 'Alert',
  'script_control.powershell_settings.console_mode': 'Block',
  'script_control.powershell_settings.control_mode': 'Block',
  'script_control_v2.exclusion_list': [
    {
      path: '/[CySc_process]/ /windows/folder/example.exe',
      type: '',
    },
    {
      path: '/test/folder/example.exe',
      type: '',
    },
    {
      path: '/test/folder/example.py',
      type: '',
    },
    {
      path: '/v2/path/dotnet',
      type: 'DotnetDlr',
    },
    {
      path: '/v2/path/js',
      type: 'Jscript',
    },
    {
      path: '/v2/path/vb',
      type: 'VbScript',
    },
  ],
  'script_control_v2.dotnet_dlr_settings.control_mode': 'Alert',
  'script_control_v2.python_settings.control_mode': 'Alert',
  'persona.admin_whitelist': [
    {
      username: 'Admin1',
    },
    {
      username: 'Admin2',
    },
    {
      username: 'Admin3',
    },
    {
      username: 'Admin4',
    },
    {
      username: 'Admin5',
    },
    {
      username: 'Admin6',
    },
    {
      username: 'Admin7',
    },
    {
      username: 'Admin8',
    },
    {
      username: 'Admin9',
    },
    {
      username: 'Admin10',
    },
    {
      username: 'Admin11',
    },
    {
      username: 'Admin12',
    },
  ],
  'persona.mitigation_actions': [
    {
      id: 'persona.mitigation_actions24',
      method: 'duo',
      threshold: '15',
      action: 'prompt2fa',
    },
    {
      id: 'persona.mitigation_actions25',
      method: '',
      threshold: '35',
      action: 'promptUsernameAndPassword',
    },
    {
      id: 'persona.mitigation_actions26',
      method: '',
      threshold: '25',
      action: 'promptUsernameAndPassword',
    },
    {
      id: 'persona.mitigation_actions27',
      method: '',
      threshold: '55',
      action: 'promptUsernameAndPassword',
    },
  ],
  'persona.mode': '1',
  'data_privacy.data_privacy[0].field': 'hostname',
  'data_privacy.data_privacy[0].enable': '0',
  'data_privacy.data_privacy[1].field': 'fqdn',
  'data_privacy.data_privacy[1].enable': '0',
  'data_privacy.data_privacy[2].field': 'username',
  'data_privacy.data_privacy[2].enable': '0',
  'data_privacy.data_privacy[3].field': 'ipv6',
  'data_privacy.data_privacy[3].enable': '0',
  'data_privacy.data_privacy[4].field': 'mac_address',
  'data_privacy.data_privacy[4].enable': '0',
  'data_privacy.data_privacy[5].field': 'distinguished_name',
  'data_privacy.data_privacy[5].enable': '0',
  'data_privacy.data_privacy[6].field': 'active_directory_information',
  'data_privacy.data_privacy[6].enable': '0',
  'data_privacy.data_privacy[7].field': 'file_owner',
  'data_privacy.data_privacy[7].enable': '0',
  'data_privacy.data_privacy[8].field': 'file_path',
  'data_privacy.data_privacy[8].enable': '0',
}

const MOCK_NEW_FLATTENED_POLICY: FlattenedDevicePolicy = {
  file_exclusions: [],
  'filetype_actions.suspicious_files[0].actions': '0',
  'filetype_actions.suspicious_files[0].file_type': 'executable',
  'filetype_actions.threat_files[0].actions': '0',
  'filetype_actions.threat_files[0].file_type': 'executable',
  policy_name: '',
  checksum: '',
  'logpolicy.retentiondays': '30',
  'logpolicy.log_upload': null,
  'logpolicy.maxlogsize': '100',
  'policy[0].name': 'auto_blocking',
  'policy[0].value': '0',
  'policy[1].name': 'auto_delete',
  'policy[1].value': '0',
  'policy[2].name': 'days_until_deleted',
  'policy[2].value': '14',
  'policy[3].name': 'auto_uploading',
  'policy[3].value': '0',
  'policy[4].name': 'pdf_auto_uploading',
  'policy[4].value': '0',
  'policy[5].name': 'ole_auto_uploading',
  'policy[5].value': '0',
  'policy[6].name': 'docx_auto_uploading',
  'policy[6].value': '0',
  'policy[7].name': 'python_auto_uploading',
  'policy[7].value': '0',
  'policy[8].name': 'autoit_auto_uploading',
  'policy[8].value': '0',
  'policy[9].name': 'powershell_auto_uploading',
  'policy[9].value': '0',
  'policy[10].name': 'threat_report_limit',
  'policy[10].value': '500',
  'policy[11].name': 'low_confidence_threshold',
  'policy[11].value': '-600',
  'policy[12].name': 'full_disc_scan',
  'policy[12].value': '0',
  'policy[13].name': 'watch_for_new_files',
  'policy[13].value': '0',
  'policy[14].name': 'memory_exploit_detection',
  'policy[14].value': '0',
  'policy[15].name': 'trust_files_in_scan_exception_list',
  'policy[15].value': '0',
  'policy[16].name': 'logpolicy',
  'policy[16].value': '0',
  'policy[17].name': 'prevent_service_shutdown',
  'policy[17].value': '0',
  'policy[18].name': 'scan_max_archive_size',
  'policy[18].value': '0',
  'policy[19].name': 'sample_copy_path',
  'policy[19].value': null,
  'policy[20].name': 'kill_running_threats',
  'policy[20].value': '0',
  'policy[21].name': 'show_notifications',
  'policy[21].value': '0',
  'policy[22].name': 'custom_thumbprint',
  'policy[22].value': null,
  'policy[23].name': 'scan_exception_list',
  'policy[23].value': [],
  'policy[24].name': 'device_control',
  'policy[24].value': '0',
  'policy[25].name': 'data_privacy',
  'policy[25].value': '0',
  'policy[26].name': 'script_control',
  'policy[26].value': '0',
  'policy[27].name': 'optics',
  'policy[27].value': '0',
  'policy[28].name': 'optics_set_disk_usage_maximum_fixed',
  'policy[28].value': '1000',
  'policy[29].name': 'optics_malware_auto_upload',
  'policy[29].value': '0',
  'policy[30].name': 'optics_memory_defense_auto_upload',
  'policy[30].value': '0',
  'policy[31].name': 'optics_script_control_auto_upload',
  'policy[31].value': '0',
  'policy[32].name': 'optics_application_control_auto_upload',
  'policy[32].value': '0',
  'policy[33].name': 'optics_sensors_dns_visibility',
  'policy[33].value': '0',
  'policy[34].name': 'optics_sensors_private_network_address_visibility',
  'policy[34].value': '0',
  'policy[35].name': 'optics_sensors_windows_event_log_visibility',
  'policy[35].value': '0',
  'policy[36].name': 'optics_sensors_advanced_powershell_visibility',
  'policy[36].value': '0',
  'policy[37].name': 'optics_sensors_advanced_wmi_visibility',
  'policy[37].value': '0',
  'policy[38].name': 'optics_sensors_advanced_executable_parsing',
  'policy[38].value': '0',
  'policy[39].name': 'optics_sensors_enhanced_process_hooking_visibility',
  'policy[39].value': '0',
  'policy[40].name': 'optics_show_notifications',
  'policy[40].value': '0',
  'policy[41].name': 'optics_sensors_intel_cryptomining_detection',
  'policy[41].value': '0',
  'script_control.global_settings.control_mode': 'Alert',
  'script_control.global_settings.allowed_folders': [],
  'script_control.powershell_settings.control_mode': 'Alert',
  'script_control.powershell_settings.console_mode': 'Allow',
  'script_control.macro_settings.control_mode': 'Alert',
  'script_control.activescript_settings.control_mode': 'Alert',
  'script_control_v2.exclusion_list': [],
  'script_control_v2.dotnet_dlr_settings.control_mode': 'Alert',
  'script_control_v2.python_settings.control_mode': 'Alert',
  'software_inventory.enabled': '0',
  'software_inventory.full_report_hours': '24',
  'memoryviolation_actions.memory_exclusion_list': [],
  'memoryviolation_actions.memory_exclusion_list_v2': [],
  'memoryviolation_actions.memory_violations[0].violation_type': 'lsassread',
  'memoryviolation_actions.memory_violations[0].action': 'Alert',
  'memoryviolation_actions.memory_violations[1].violation_type': 'outofprocessunmapmemory',
  'memoryviolation_actions.memory_violations[1].action': 'Alert',
  'memoryviolation_actions.memory_violations[2].violation_type': 'stackpivot',
  'memoryviolation_actions.memory_violations[2].action': 'Alert',
  'memoryviolation_actions.memory_violations[3].violation_type': 'stackprotect',
  'memoryviolation_actions.memory_violations[3].action': 'Alert',
  'memoryviolation_actions.memory_violations[4].violation_type': 'outofprocessoverwritecode',
  'memoryviolation_actions.memory_violations[4].action': 'Alert',
  'memoryviolation_actions.memory_violations[5].violation_type': 'outofprocesscreatethread',
  'memoryviolation_actions.memory_violations[5].action': 'Alert',
  'memoryviolation_actions.memory_violations[6].violation_type': 'overwritecode',
  'memoryviolation_actions.memory_violations[6].action': 'Alert',
  'memoryviolation_actions.memory_violations[7].violation_type': 'outofprocesswritepe',
  'memoryviolation_actions.memory_violations[7].action': 'Alert',
  'memoryviolation_actions.memory_violations[8].violation_type': 'outofprocessallocation',
  'memoryviolation_actions.memory_violations[8].action': 'Alert',
  'memoryviolation_actions.memory_violations[9].violation_type': 'outofprocessmap',
  'memoryviolation_actions.memory_violations[9].action': 'Alert',
  'memoryviolation_actions.memory_violations[10].violation_type': 'outofprocesswrite',
  'memoryviolation_actions.memory_violations[10].action': 'Alert',
  'memoryviolation_actions.memory_violations[11].violation_type': 'outofprocessapc',
  'memoryviolation_actions.memory_violations[11].action': 'Alert',
  'memoryviolation_actions.memory_violations_ext[0].violation_type': 'dyldinjection',
  'memoryviolation_actions.memory_violations_ext[0].action': 'Alert',
  'memoryviolation_actions.memory_violations_ext[1].violation_type': 'trackdataread',
  'memoryviolation_actions.memory_violations_ext[1].action': 'Alert',
  'memoryviolation_actions.memory_violations_ext[2].violation_type': 'zeroallocate',
  'memoryviolation_actions.memory_violations_ext[2].action': 'Alert',
  'memoryviolation_actions.memory_violations_ext[3].violation_type': 'maliciouspayload',
  'memoryviolation_actions.memory_violations_ext[3].action': 'Alert',
  'memoryviolation_actions.memory_violations_ext_v2[0].violation_type': 'doppelganger',
  'memoryviolation_actions.memory_violations_ext_v2[0].action': 'None',
  'memoryviolation_actions.memory_violations_ext_v2[1].violation_type': 'oopprotect',
  'memoryviolation_actions.memory_violations_ext_v2[1].action': 'None',
  'memoryviolation_actions.memory_violations_ext_v2[2].violation_type': 'childprocessprotect',
  'memoryviolation_actions.memory_violations_ext_v2[2].action': 'None',
  'memoryviolation_actions.memory_violations_ext_v2[3].violation_type': 'syscallprobe',
  'memoryviolation_actions.memory_violations_ext_v2[3].action': 'None',
  'memoryviolation_actions.memory_violations_ext_v2[4].violation_type': 'directsyscall',
  'memoryviolation_actions.memory_violations_ext_v2[4].action': 'None',
  'memoryviolation_actions.memory_violations_ext_v2[5].violation_type': 'systemdllwrite',
  'memoryviolation_actions.memory_violations_ext_v2[5].action': 'None',
  'memoryviolation_actions.memory_violations_ext_v2[6].violation_type': 'stolensystemtoken',
  'memoryviolation_actions.memory_violations_ext_v2[6].action': 'None',
  'memoryviolation_actions.memory_violations_ext_v2[7].violation_type': 'dangerousenvvariable',
  'memoryviolation_actions.memory_violations_ext_v2[7].action': 'None',
  'memoryviolation_actions.memory_violations_ext_v2[8].violation_type': 'maliciouslowintegrity',
  'memoryviolation_actions.memory_violations_ext_v2[8].action': 'None',
  'memoryviolation_actions.memory_violations_ext_v2[9].violation_type': 'dangerouscomobject',
  'memoryviolation_actions.memory_violations_ext_v2[9].action': 'None',
  'memoryviolation_actions.memory_violations_ext_v2[10].violation_type': 'injectionviaapc',
  'memoryviolation_actions.memory_violations_ext_v2[10].action': 'None',
  'memoryviolation_actions.memory_violations_ext_v2[11].violation_type': 'runmacroscript',
  'memoryviolation_actions.memory_violations_ext_v2[11].action': 'None',
  'appcontrol.changewindow_enabled': '0',
  'appcontrol.allowed_folders': [],
  'appcontrol.lockdown': [],
  'device_control.configurations[0].device_class': 'AndroidUSB',
  'device_control.configurations[0].control_mode': 'FullAccess',
  'device_control.configurations[1].device_class': 'iOS',
  'device_control.configurations[1].control_mode': 'FullAccess',
  'device_control.configurations[2].device_class': 'StillImage',
  'device_control.configurations[2].control_mode': 'FullAccess',
  'device_control.configurations[3].device_class': 'USBCDDVDRW',
  'device_control.configurations[3].control_mode': 'FullAccess',
  'device_control.configurations[4].device_class': 'USBDrive',
  'device_control.configurations[4].control_mode': 'FullAccess',
  'device_control.configurations[5].device_class': 'VMWareMount',
  'device_control.configurations[5].control_mode': 'FullAccess',
  'device_control.configurations[6].device_class': 'WPD',
  'device_control.configurations[6].control_mode': 'FullAccess',
  'device_control.exclusion_list': [],
  'data_privacy.data_privacy[0].field': 'hostname',
  'data_privacy.data_privacy[0].enable': '0',
  'data_privacy.data_privacy[1].field': 'fqdn',
  'data_privacy.data_privacy[1].enable': '0',
  'data_privacy.data_privacy[2].field': 'username',
  'data_privacy.data_privacy[2].enable': '0',
  'data_privacy.data_privacy[3].field': 'ipv6',
  'data_privacy.data_privacy[3].enable': '0',
  'data_privacy.data_privacy[4].field': 'mac_address',
  'data_privacy.data_privacy[4].enable': '0',
  'data_privacy.data_privacy[5].field': 'distinguished_name',
  'data_privacy.data_privacy[5].enable': '0',
  'data_privacy.data_privacy[6].field': 'active_directory_information',
  'data_privacy.data_privacy[6].enable': '0',
  'data_privacy.data_privacy[7].field': 'file_owner',
  'data_privacy.data_privacy[7].enable': '0',
  'data_privacy.data_privacy[8].field': 'file_path',
  'data_privacy.data_privacy[8].enable': '0',
  'persona.admin_whitelist': [],
  'persona.mitigation_actions': [],
  'persona.mode': '0',
}

export { MOCK_EXISTING_FLATTENED_POLICY, MOCK_NEW_FLATTENED_POLICY }
