export enum AriaElementLabel {
  AddAppIdsIconButton = 'add-app-ids-icon-button',
  AddApplicationIdIconButton = 'add-app-id-icon-button',
  AddCidrAddressIconButton = 'add-cidr-address-icon-button',
  ConnectorWidgetHealthStatus = 'connector-widget-health-status',
  DiscardChangesButton = 'discard-changes-button',
  DropdownIconButton = 'dropdown-icon-button',
  EventsInfiniteTable = 'events-infinite-table',
  FormButtonPanel = 'components:drawer.formButtonPanel',
  EntityDetailsSaveButton = 'entity-details-save-button',
  HealthCheckDesc = 'health-check-desc',
  InfiniteTable = 'infinite-table',
  InputGroupAddButton = 'add-input-group-button',
  NetworkServiceDetails = 'network-service-details',
  SettingsSourceIpAnchoringView = 'settings-source-ip-anchoring-view',
  StickyActionsSaveButton = 'sticky-actions-save-button',
  TargetSetShowDestinationTooltipButton = 'show-destination-tooltip-button',
  TargetSetShowProtocolTooltipButton = 'show-protocol-tooltip-button',
  UnsavedChangesCancelButton = 'unsaved-changes-cancel-button',
  UnsavedChangesConfirmButton = 'unsaved-changes-confirm-button',
}
