export const FORMS = {
  CREATE_EDIT_USER: 'CREATE_EDIT_USER',
  CREATE_EDIT_PARTNER: 'CREATE_EDIT_PARTNER',
  CREATE_EDIT_ROLE: 'CREATE_EDIT_ROLE',
  CREATE_EDIT_TENANT: 'CREATE_EDIT_TENANT',
  CREATE_EDIT_TENANT_USER: 'CREATE_EDIT_TENANT_USER',
  CREATE_EDIT_PARTNER_APP: 'CREATE_EDIT_PARTNER_APP',
}
