/*
 *   Copyright (c) 2021 BlackBerry Ltd
 *   All rights reserved.
 *   BlackBerry Limited proprietary and confidential.
 *   Do not reproduce without permission in writing.
 */
export enum HelpLinks {
  ActivationSettings = 'activation',
  Alerts = 'gateway-alerts',
  AssetsMobileDevices = 'assets-mobile-devices',
  AssetsPersonaUsers = 'assets-persona-users',
  AssetsUserGroups = 'assets-user-groups',
  AssetsUsers = 'assets-users',
  AuthenticationPolicy = 'gateway-authentication-policy',
  AuthenticationSettings = 'authentication',
  ClientDNS = 'gateway-dns-suffix',
  ConnectivityNode = 'connectivity-node',
  CronosDashboard = 'dashboard',
  Dashboard = 'gateway-dashboard',
  DirectoryConnections = 'connect-directory',
  DirectoryInfo = 'link-directory',
  DlpContentPolicy = 'avert-info-protection-policy',
  DlpMobilePolicy = 'dlp-mobile-policy',
  EmmAppConfig = 'emm-app-config',
  EmmConnection = 'emm-connection',
  Enrollment = 'gateway-enrollment-policy',
  Enrollment_Cronos = 'enrollment-policy',
  GatewayACL = 'gateway-access-control-list',
  GatewayConnectors = 'gateway-connectors',
  GatewayIPRange = 'gateway-ip-range',
  GatewayNetworkActivity = 'gateway-network-activity',
  GatewayNetworkEvents = 'gateway-network-events',
  GatewayService = 'gateway-service-policy',
  MobileDeviceThreats = 'gateway-mdt-policy',
  NetworkAccessControl = 'gateway-nac-policy',
  NetworkProtection = 'gateway-network-protection',
  NetworkServices = 'gateway-network-services',
  PersonaDesktopStats = 'persona-desktop-stats',
  PoliciesAdaptiveResponse = 'gateway-policies-adaptive-response',
  PoliciesRiskDetection = 'risk-assessment-policy',
  PrivateNetworkDNS = 'gateway-private-dns',
  PrivateNetworkRouting = 'gateway-private-network',
  ProtectMobileAlerts = 'protect-mobile-alerts',
  ProtectMobilePolicy = 'protect-mobile-policy',
  ProtectMobileSafeUnsafeList = 'protect-mobile-safe-unsafe-list',
  SettingsAdaptiveResponse = 'gateway-settings-adaptive-response',
  SourceIPAnchoring = 'gateway-source-ip-anchoring',
  Vulnerabilities = 'vulnerabilities',
  AvertDataCollection = 'avert-data-collection',
  AvertAllowedDomains = 'avert-allowed-domains',
  AvertTemplates = 'avert-templates',
  AvertDataTypes = 'avert-data-types',
  AvertTrustedCertificates = 'avert-trusted-certificates',
  AvertNotifications = 'avert-notifications',
  AvertEvents = 'avert-events',
  AvertFileInventory = 'avert-file-inventory',
}
