export const mockToken = {
  tenantid: 'c301bb46-c80e-4b7b-9653-ca3535ed2eea',
  userlogin: 'demo@ahem.sw.rim.net',
  userid: '26a36fec-1d0a-4fde-a06f-d6eb1db2cc18',
  ghostusername: null,
  tenantdefaultstype: 0,
  shardid: 1,
  scp: [
    'agentupdate:create',
    'agentupdate:delete',
    'agentupdate:read',
    'agentupdate:update',
    'application:read',
    'auditlog:read',
    'certificatestorage:read',
    'customauthentication:read',
    'dashboard:read',
    'device:create',
    'device:delete',
    'device:read',
    'device:update',
    'devicemanagement:create',
    'devicemanagement:delete',
    'devicemanagement:read',
    'devicemanagement:update',
    'globallist:create',
    'globallist:delete',
    'globallist:read',
    'globallist:update',
    'installationtoken:read',
    'installerdownload:read',
    'integrations:create',
    'integrations:delete',
    'integrations:read',
    'integrations:update',
    'invitationurl:read',
    'invitationurl:update',
    'optics:create',
    'optics:delete',
    'optics:read',
    'optics:update',
    'persona:read',
    'policy:create',
    'policy:delete',
    'policy:list',
    'policy:read',
    'policy:update',
    'reportssite:read',
    'settings:read',
    'supportlogin:read',
    'syslogsiem:read',
    'threatdatareport:read',
    'threats:list',
    'threats:read',
    'threats:update',
    'uninstallpasswordmanagement:read',
    'uninstallpasswordmanagement:update',
    'user:create',
    'user:delete',
    'user:read',
    'user:update',
    'zone:create',
    'zone:delete',
    'zone:read',
    'zone:update',
  ],
  eecoid: 'AsJ75TK6SeSi3/XMZcpcoew=',
  role: [{ name: 'administrator', isCustom: false, zoneids: [], rbac: {} }],
  jti: '839e52ae-def7-4c8d-bf48-c7501b73a0f0',
  iat: (Date.now() - 1e5) * 1000,
  nbf: 1620868863,
  exp: Date.now() * 1000,
  iss: 'cylance.com',
}

export const mockSession = {
  current: {
    userId: 'AsJ75TK6SeSi3/XMZcpcoew=',
    userIdVenue: '26a36fec-1d0a-4fde-a06f-d6eb1db2cc18',
    actor: null,
    tenantIdVenue: 'c301bb46-c80e-4b7b-9653-ca3535ed2eea',
    shardId: 1,
    permissions: [
      'agentupdate:create',
      'agentupdate:delete',
      'agentupdate:read',
      'agentupdate:update',
      'application:read',
      'auditlog:read',
      'certificatestorage:read',
      'customauthentication:read',
      'dashboard:read',
      'device:create',
      'device:delete',
      'device:read',
      'device:update',
      'devicemanagement:create',
      'devicemanagement:delete',
      'devicemanagement:read',
      'devicemanagement:update',
      'globallist:create',
      'globallist:delete',
      'globallist:read',
      'globallist:update',
      'installationtoken:read',
      'installerdownload:read',
      'integrations:create',
      'integrations:delete',
      'integrations:read',
      'integrations:update',
      'invitationurl:read',
      'invitationurl:update',
      'optics:create',
      'optics:delete',
      'optics:read',
      'optics:update',
      'persona:read',
      'policy:create',
      'policy:delete',
      'policy:list',
      'policy:read',
      'policy:update',
      'reportssite:read',
      'settings:read',
      'supportlogin:read',
      'syslogsiem:read',
      'threatdatareport:read',
      'threats:list',
      'threats:read',
      'threats:update',
      'uninstallpasswordmanagement:read',
      'uninstallpasswordmanagement:update',
      'user:create',
      'user:delete',
      'user:read',
      'user:update',
      'zone:create',
      'zone:delete',
      'zone:read',
      'zone:update',
    ],
    tenantDefaultsType: 0,
    loggedIn: true,
    token: mockToken,
    accessTokenVenue: `eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.${btoa(
      JSON.stringify(mockToken),
    )}.dZkHj-Io2Co510iv-eW4cAxtspWP28dFDzYLAMiHmW4`,
    verificationTokenVenue:
      'JESBvOfJk05hoT2nN3XLKDYNIMKVZ4JDSPPvw8U_XfWIQHe8o_7Ae9yqKT_2yqmqRthmH9rHL7SED1P-AguaBfcDY_KRqtirU0M86LxBktEQTIGw0N_T6dQv_rxPHfvlWcbV8fxn5PQGVXrd-sP2dQ2:xgiA2igE_dhwA4nWci-VfpWY9s5hh7uLKwb6zT6gCKO7RPil-uY5thMA23WKaiFAG7Ct1jsbsRY1omYMHcOeQay72u19xmTJu4oz8lrnXA4XTYrJADb0dbL7g2_Gj7DmLdJBtt2DR9EBLCxdtdGlUgyZYxWMRDksIC-3FBaln8w1',
    tokenExpirationTime: 1620872463000,
    email: 'demo@ahem.sw.rim.net',
  },
}

export const acquireVenueSession = jest.fn().mockImplementation(async () => {
  return mockSession
})
export const refreshVenueSession = jest.fn().mockImplementation(async () => {
  return mockSession
})
